%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Name of the programmer: Abraham %
% Date: 2018-03-23                %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Purpose
% Compute the reach-avoid probability using Genz's code

%% Inputs
% initial_state                                                 : x_0\in SafeSet under evaluation
% input_vector                                                  : Input vector under evaluation
% concatenated_state_mean_no_input_and_no_initial_state_effect  : G_matrix * disturbance_mean_concatenated_vector
% concatenated_state_sigma                                      : Sigma of the concatenated state vector
% H_matrix_without_initial_state                                : H_matrix * U + concatenated_state_mean_without_initial_state = concatenated_state_mean
% reachAvoidTube_A                                              : Matrix A for the linear inequalities describing the polytopic reach-avoid tube
% reachAvoidTube_b                                              : Vector b for the linear inequalities describing the polytopic reach-avoid tube
% state_dimension                                               : n of the system
% myeps                                                         : Tolerance for the Genz's algorithm's error estimate

%% Outputs
% prob                                                          : \hat{r}_{\overline{x}_0}^U (Eqn 11/12 in the NAASS 2018 paper)

%% Notes
% This function serves as the oracle for safety probability in the optimization problems
% Assumes initial state is correct (We can check it easily but at the cost of computational time)
% Calls RAprob_CWH to compute the probability
function [prob] = reachAvoidCostFunctionAssumingValidInitialState_CWH(initial_state,...
                                          input_vector,...
                                          concatenated_A_matrix,...
                                          concatenated_state_mean_no_input_and_no_initial_state_effect,...
                                          concatenated_state_sigma,...
                                          H_matrix_without_initial_state,...
                                          reachAvoidTube_A,...
                                          reachAvoidTube_b,...
                                          state_dimension,...
                                          myeps)
    % State stochastics computation
    concatentated_state_natural_dynamics_for_initial_state = concatenated_A_matrix*initial_state;
    concatenated_state_mean_with_initial_state_no_input = concatenated_state_mean_no_input_and_no_initial_state_effect ...
                                    +concatentated_state_natural_dynamics_for_initial_state;
    concatenated_state_mean_no_input=concatenated_state_mean_with_initial_state_no_input(state_dimension+1:end);

    prob = RAprob_CWH(input_vector,...
                    concatenated_state_mean_no_input,...
                    concatenated_state_sigma,...
                    H_matrix_without_initial_state,...
                    reachAvoidTube_A,...
                    reachAvoidTube_b,...
                    state_dimension,...
                    myeps);            
end
